//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PracenjeVozila
{
    using System;
    using System.Collections.Generic;
    
    public partial class PutniRadniList
    {
        public PutniRadniList()
        {
            this.lokacija = new HashSet<lokacija>();
            this.radni_sati = new HashSet<radni_sati>();
        }
    
        public int id_putnog_radnog_lista { get; set; }
        public int vozilo { get; set; }
        public int kreira { get; set; }
        public Nullable<int> kilometraza { get; set; }
        public Nullable<System.DateTime> pocetak { get; set; }
        public Nullable<System.DateTime> kraj { get; set; }
        public string mjesto_utovara { get; set; }
        public string mjesto_istovara { get; set; }
        public Nullable<int> teret { get; set; }
        public string napomene { get; set; }
    
        public virtual ICollection<lokacija> lokacija { get; set; }
        public virtual zaposlenici zaposlenici { get; set; }
        public virtual ICollection<radni_sati> radni_sati { get; set; }
        public virtual vozilo vozilo1 { get; set; }
    }
}
