//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PracenjeVozila
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class T25_DBEntities : DbContext
    {
        public T25_DBEntities()
            : base("name=T25_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<godisnji_odmor> godisnji_odmor { get; set; }
        public DbSet<lokacija> lokacija { get; set; }
        public DbSet<PutniRadniList> PutniRadniList { get; set; }
        public DbSet<radni_sati> radni_sati { get; set; }
        public DbSet<servis> servis { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<tehnicki_pregled> tehnicki_pregled { get; set; }
        public DbSet<uloga> uloga { get; set; }
        public DbSet<vozilo> vozilo { get; set; }
        public DbSet<vrsta_vozila> vrsta_vozila { get; set; }
        public DbSet<zaposlenici> zaposlenici { get; set; }
    }
}
