//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesingPi
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class T25_DBEntities1 : DbContext
    {
        public T25_DBEntities1()
            : base("name=T25_DBEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<godisnji_odmor> godisnji_odmor { get; set; }
        public virtual DbSet<lokacija> lokacija { get; set; }
        public virtual DbSet<PutniRadniList> PutniRadniList { get; set; }
        public virtual DbSet<radni_sati> radni_sati { get; set; }
        public virtual DbSet<servis> servis { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tehnicki_pregled> tehnicki_pregled { get; set; }
        public virtual DbSet<uloga> uloga { get; set; }
        public virtual DbSet<vozilo> vozilo { get; set; }
        public virtual DbSet<vrsta_vozila> vrsta_vozila { get; set; }
        public virtual DbSet<zaposlenici> zaposlenici { get; set; }
    }
}
