//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesingPi
{
    using System;
    using System.Collections.Generic;
    
    public partial class zaposlenici
    {
        public zaposlenici()
        {
            this.godisnji_odmor = new HashSet<godisnji_odmor>();
            this.PutniRadniList = new HashSet<PutniRadniList>();
            this.radni_sati = new HashSet<radni_sati>();
        }
    
        public int id_zaposlenici { get; set; }
        public Nullable<int> uloga { get; set; }
        public string ime { get; set; }
        public string prezime { get; set; }
        public string lozinka { get; set; }
        public string korisnicko_ime { get; set; }
        public string oib { get; set; }
        public Nullable<System.DateTime> datum_zaposlenja { get; set; }
        public string IBAN { get; set; }
        public string telefon { get; set; }
        public string adresa { get; set; }
        public Nullable<System.DateTime> datum_rodjenja { get; set; }
    
        public virtual ICollection<godisnji_odmor> godisnji_odmor { get; set; }
        public virtual ICollection<PutniRadniList> PutniRadniList { get; set; }
        public virtual ICollection<radni_sati> radni_sati { get; set; }
        public virtual uloga uloga1 { get; set; }
    }
}
