//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesingPi
{
    using System;
    using System.Collections.Generic;
    
    public partial class tehnicki_pregled
    {
        public int id_tehnickog_pregleda { get; set; }
        public Nullable<int> vozilo { get; set; }
        public Nullable<System.DateTime> datum { get; set; }
    
        public virtual vozilo vozilo1 { get; set; }
    }
}
