//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesingPi
{
    using System;
    using System.Collections.Generic;
    
    public partial class vozilo
    {
        public vozilo()
        {
            this.dnevnik = new HashSet<dnevnik>();
            this.PutniRadniList = new HashSet<PutniRadniList>();
            this.servis = new HashSet<servis>();
            this.tehnicki_pregled = new HashSet<tehnicki_pregled>();
        }
    
        public int id_vozilo { get; set; }
        public Nullable<int> vrsta_vozila_id { get; set; }
        public string naziv { get; set; }
        public Nullable<int> godina_proizvodnje { get; set; }
        public string registracija { get; set; }
        public Nullable<System.DateTime> datum_registracije { get; set; }
        public Nullable<int> pocetno_stanje_km { get; set; }
        public Nullable<int> nosivost { get; set; }
        public Nullable<int> servisni_interval { get; set; }
    
        public virtual ICollection<dnevnik> dnevnik { get; set; }
        public virtual ICollection<PutniRadniList> PutniRadniList { get; set; }
        public virtual ICollection<servis> servis { get; set; }
        public virtual ICollection<tehnicki_pregled> tehnicki_pregled { get; set; }
        public virtual vrsta_vozila vrsta_vozila { get; set; }
    }
}
