//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesingPi
{
    using System;
    using System.Collections.Generic;
    
    public partial class status
    {
        public status()
        {
            this.dnevnik = new HashSet<dnevnik>();
        }
    
        public int id_statusa { get; set; }
        public string naziv { get; set; }
    
        public virtual ICollection<dnevnik> dnevnik { get; set; }
    }
}
