//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesingPi
{
    using System;
    using System.Collections.Generic;
    
    public partial class vrsta_goriva
    {
        public vrsta_goriva()
        {
            this.tankiranje = new HashSet<tankiranje>();
        }
    
        public int id_vrste_goriva { get; set; }
        public string naziv { get; set; }
    
        public virtual ICollection<tankiranje> tankiranje { get; set; }
    }
}
